base_info:
  title: Henry's Blog
  author: Henry
  url: https://liheng.website

style:
#  primary_color: '#3eaf7c'
  avatar: /images/avatar.svg
  favicon: /images/favicon.ico
  article_img_align: center
#  right_side_width: 300px
#  content_max_width: 800px
#  nav_color:
#    left: "#f78736" #left side
#    right: "#367df7"  #right side
#    transparency: 35 #percent (10-99)
  hover: scale
  first_screen:
    enable: true
    description: "Henry's Blog"
#    background_image:
#      light: https://bing.img.run/1920x1080.php

social_contact: # social contact icons in the first screen, you can add more by using fontawesome icon names
  enable: true
  links:
    github: https://github.com/henry-hub
    zhihu: https://www.zhihu.com/people/ihub
    twitter: https://twitter.com/henryli93
    email: henry.box@outlook.com

menu: #you can customize, i18n files are in the theme's languages folder. fa-regular recommended
  Home:
    path: /
    icon: fa-regular fa-house # can be empty
  Archives:
    path: /archives
    icon: fa-regular fa-archive # can be empty
  # Status:
  #   path: https://status.evanluo.top/
  #   icon: fa-regular fa-chart-bar
  # About:
  #   icon: fa-regular fa-user
  #   submenus:
  #     Me: /about
  #     Github: https://github.com/EvanNotFound/hexo-theme-redefine
  #     Blog: https://www.evanluo.top
  #     Friends: /friends
  # Links:
  #   icon: fa-regular fa-link
  #   submenus:
  #     Link1: /link1
  #     Link2: /link2
  #     Link3: /link3
